### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by adayim** [adayim/forestploter#1]
Planning functionalities:

- [x] Able log odds options.
- [x] Able to add titles on the top
- [x] Able to add x-axis title
- [x] `add_text` accept text vector
- [x] Different `xlim` for different group

**Comment by ParsaAkbari** [comment]
Further suggestions:
- [ ] option change ref_line across different CI columns
- [ ] option to change xlog across different CI columns

**Comment by adayim** [comment]
> Further suggestions:
> 
> * [x]  option change ref_line across different CI columns
> * [x]  option to change xlog across different CI columns

Accept atomic vector for different CI columns now.
