### ISSUE TITLE
Allow summary rows when plotting multiple CI columns

### ISSUE THREAD

**Issue by Rscho314** [adayim/forestploter#13]
Hi,

First, congrats for your package! I think it does indeed succeed in terms of flexibility and ease of use.

I'd like to see summary rows implemented when plotting multiple CI columns. I might attempt implementing it myself, although I'm not sure I'm really up to the task. I thought about just attempting to hack theme parameters as a 1st attempt.

Would you have any advice on where to begin for implementing such a feature?

Cheers!

**Comment by adayim** [comment]
Hi, I'm not sure I understand what you mean here. If you want to add more summary numbers, just put it in the data and leave the columns blank where you want to add CI columns. If the CI columns are grouped, you can paste multiple summary data together and separate it with linebreak.

**Comment by Rscho314** [comment]
I might have a terminology issue here. I thought you called the plot column 'Ci column' but I misunderstood, apparently.

What I'd like is to have multiple plot columns with multiple summary rows in each column, *i.e.* have the `is_summary` parameter vector of the `forest` function roll over to multiple columns like `est`, `lower` and `upper`. The docs state that

> `is_summary` can not be used with multiple group `forestplot`

That's what I'd like to do.

**Comment by adayim** [comment]
I understand you now. But I don't quite get why you want add two or more diamond shapes in one cell? Don't you think it's too crowded? I am not sure I have strong reason to do this.

**Comment by Rscho314** [comment]
Basically, I'm aiming at a forest plot with multiple row/study subgroups (already available from your package), like this:

![Forest-plot-and-meta-analysis-of-all-cause-death.png](https://user-images.githubusercontent.com/8514467/181645699-a49ea97a-872b-43b8-b1bc-d9855f848a20.png)

... but with multiple plot columns. It's for a diagnostic test accuracy meta-analysis, so I need plot columns for sensitivity, specificity, etc. Like this:

![Forest-plot-of-the-diagnostic-accuracy-of-CT-in-the-identification-of-lumbar-disc.png](https://user-images.githubusercontent.com/8514467/181646356-c8f296f9-1456-4f3b-8401-9faa816d16b9.png)

...but with summary rows for each subgroup of studies, as the previous image.

I hope it's clearer, now?

**Comment by adayim** [comment]
Em, I see. I think the group means you put two or more confidence interval in one cell, as it is shown in the last example of readme. 
I don't know if the following is what you want?
```r
p <- forest(dt[,c(1:2, 20, 3, 22)],
            est = list(dt$est_gp1,
                       dt$est_gp2),
            lower = list(dt$low_gp1,
                         dt$low_gp2),
            upper = list(dt$hi_gp1,
                         dt$hi_gp2),
            ci_column = c(3, 5),
            is_summary = c(rep(FALSE, nrow(dt_tmp)-1), TRUE),
            ref_line = 1,
            arrow_lab = c("Placebo Better", "Treatment Better"),
            nudge_y = 0.2,
            xlim = c(0, 4))
```
![forest](https://user-images.githubusercontent.com/5401293/181715347-dc2b7984-d1cf-4483-9492-9eb28b6f8995.png)

**Comment by Rscho314** [comment]
Ok, I got confused by a mistake in my code, read the docs on `is_summary` and the context made it even more confusing. This works perfectly. I'm closing the issue.

Thanks a lot, I'm very sorry I wasted your time!

**Comment by Rscho314** [comment]
Ok, I got confused by a mistake in my code, read the docs on `is_summary` and the context made it even more confusing. This works perfectly. I'm closing the issue.

Thanks a lot, I'm very sorry I wasted your time!
