### ISSUE TITLE
Would it be possible to remove the legend?

### ISSUE THREAD

**Issue by Yufeng88** [adayim/forestploter#14]
Hi Adayim,
Thanks for this great package. It seems the legend is always present when create a forest plot with CIs by groups. I'm wondering whether the group legend can be removed, because I'd like to combine more than two forest plots with a shared legend.

Thanks a lot,
Yufeng

**Comment by adayim** [comment]
You can set `legend_position = "none"` to suppress the legend now.

**Comment by Yufeng88** [comment]
Super nice! Tons of thanks for your time !
