### ISSUE TITLE
how to save as a pdf file which could change the size of picture when set different width and height?

### ISSUE THREAD

**Issue by Magetutor** [adayim/forestploter#16]
Hi Adayim! 

Thank you for developed such an excellent package, which makes it easy to draw a forestplot. When I export the figures, something happened which make the exported figures just as a fixed size. But i want save it use different width and height  in pdf() function ot use ggsave() function. Now, i set different width and height make no changes for the export figures. What should i do to solve this problem? 
my code :
```
pdf('Figure1_CKD risk factors.pdf',width = 8,height = 5)
print(a)
dev.off()
```
my figure:
<img width="569" alt="1661654311520" src="https://user-images.githubusercontent.com/63154430/187055069-1b5691f5-407d-4de0-ab8f-d04764da49cb.png">

Thank you again for this great package and have a nice day!

**Comment by adayim** [comment]
Hi,

Sorry, the plotting function calculates the elements provided. The width and height of the plot is determined by the data you provided. I have been trying to find a better solution for this, but can't find a better one. There's a new function in the `dev` branch you can try it out. On it's way to CRAN now. Use `get_wh` to get the width and height of the plot and use this width and height save the plot.

```r
p_wh <- get_wh(a)
pdf('Figure1_CKD risk factors.pdf', width = p_wh[1], height = p_wh[2])
plot(a)
dev.off()
```
This will not give you a width and height you want, but still better than finding the correct width and height mannualy.

**Comment by Guiquan-27** [comment]
> Hi,
> 
> Sorry, the plotting function calculates the elements provided. The width and height of the plot is determined by the data you provided. This means the size of the plot is fixed. I have been trying to find a better solution for this, but can't find a better one. There's a new function you can try, it's on CRAN now. Use `get_wh` to get the width and height of the plot and use this width and height save the plot.
> 
> ```r
> p_wh <- get_wh(a)
> pdf('Figure1_CKD risk factors.pdf', width = p_wh[1], height = p_wh[2])
> plot(a)
> dev.off()
> ```
> 
> This will not give you a width and height you want, but still better than finding the correct width and height mannualy.

Hi, there is indeed no such <get_wh> function.

**Comment by adayim** [comment]
You should use version 0.1.8. Maybe you are using version 0.1.7. Please try again with the newer version.

**Comment by adayim** [comment]
> > Hi,
> > Sorry, the plotting function calculates the elements provided. The width and height of the plot is determined by the data you provided. This means the size of the plot is fixed. I have been trying to find a better solution for this, but can't find a better one. There's a new function you can try, it's on CRAN now. Use `get_wh` to get the width and height of the plot and use this width and height save the plot.
> > ```r
> > p_wh <- get_wh(a)
> > pdf('Figure1_CKD risk factors.pdf', width = p_wh[1], height = p_wh[2])
> > plot(a)
> > dev.off()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This will not give you a width and height you want, but still better than finding the correct width and height mannualy.
> 
> Hi, there is indeed no such <get_wh> function.

You should use version 0.1.8. Maybe you are using version 0.1.7. Please try again with the newer version.
