### ISSUE TITLE
The sizes argument would not change even a unit is given

### ISSUE THREAD

**Issue by Guiquan-27** [adayim/forestploter#17]
Firstly, thanks for your dedication in forest plot with r.
Actually, when I customized the size of point estimation in unit, the output plot would not change at all.

**Comment by adayim** [comment]
This is not helpful. Please give me exactly what you did and what you want to achieve please!

**Comment by adayim** [comment]
Thank you. I see what you mean. I found out it does not work for single value. I will fix this, thank you for reporting.
