### ISSUE TITLE
Something wrong with the CIs

### ISSUE THREAD

**Issue by JielongWu2021** [adayim/forestploter#19]
![image](https://user-images.githubusercontent.com/91595755/191529859-7d7f8a30-8b4b-47c6-bfb7-57982d6c7812.png)

Something wrong with the CIs !!!
Only the first line shows the pch symbol.
Help!!!

**Comment by adayim** [comment]
Thanks for reporting this. I don't know why the tests didn't work. I have fixed it, will submit to CRAN this weekend.

**Comment by pppaular** [comment]
Thank you for your working.
I recently came across the same issue, help!

**Comment by adayim** [comment]
My bad, sorry. I am going to submit the updated package soon to the CRAN. Can you try tu install from Github and let me know if it solved your problem?

> Thank you for your working. I recently came across the same issue, help!

**Comment by pppaular** [comment]
Thank you very much, i installed it from the Github and have solved  the CIs problem!!
