### ISSUE TITLE
How to change the line width and the style of CI?

### ISSUE THREAD

**Issue by jiangaimin1995** [adayim/forestploter#2]
Thank you very much for providing us with this elegant package for forest plot visualization. Although we coudl use edit_plot function to edit some elements of the figure, there is a problem when i used this function.
I want to add short vertical bar at the begining and the ending of the CI line. Although there is lineend paremeter, it seems that it dosen't  work when i added this parameter in edit_plot function bu using the following code:
edit_plot(p,  row = c(1, 3, 4),   gp=gpar(col="red",lwd=3,lineend="round")). 
I also tried to change the line with of these CI lines. However, it failed again. So, i would like to appreciate it if you could solve this problem. Thank you again for your contribution. We are looking forward to hearing more excellent funtions of this package.

**Comment by adayim** [comment]
Hi Aimin,

Thank you for reporting this. Sorry about the confusion of the `edit_plot` function. It's for editing the text and background of the forest plot. You can't edit any other elements.

I will add some vertical line end and CI width option to the forest plot theme.

**Comment by jiangaimin1995** [comment]
Thank you. Looking forward to the update.

**Comment by adayim** [comment]
I have added some options, now you should be able to change the line width of the confidence interval and T end at the line end now. This can be done by setting themes:
```r
tm <- forest_theme(ci_lwd = 1.5, # Set the line width of the confidence interval
                   ci_Theight = 0.2, # Set an T end at the end of CI 
)
pt <- forest(dt[,c(1:3, 8:9)],
            est = dt$est,
            lower = dt$low, 
            upper = dt$hi,
            ci_column = 4, 
            theme = tm) # Set the forest plot theme
```

Can you try this with the updated version in the GitHub and let me know? Thank you.

**Comment by jiangaimin1995** [comment]
Thank you very much, it works. The forestplot generated by the updated package is so beautiful now.
