### ISSUE TITLE
How to plot points/whiskers different colors on the same plot?

### ISSUE THREAD

**Issue by nicholekulikowski** [adayim/forestploter#20]
Hi there! I would like to color certain rows of my plot different colors- the edit_plot() function allows me to do this for the text in the row (i.e. edit_plot(fp, row = c(3, 7, 8, 9, 11), gp = gpar(col = "red", fill = "red")), but I need the points to also be the corresponding color (red, in this example). Is there any way to achieve this? Here is an example of a plot I made (I need the points and whiskers to also be red on the corresponding rows)
![image](https://user-images.githubusercontent.com/66396190/192320980-8f76ff76-b6d5-4b5f-bb58-421b485588f6.png)

**Comment by adayim** [comment]
> Hi there! I would like to color certain rows of my plot different colors- the edit_plot() function allows me to do this for the text in the row (i.e. edit_plot(fp, row = c(3, 7, 8, 9, 11), gp = gpar(col = "red", fill = "red")), but I need the points to also be the corresponding color (red, in this example). Is there any way to achieve this? Here is an example of a plot I made (I need the points and whiskers to also be red on the corresponding rows) ![image](https://user-images.githubusercontent.com/66396190/192320980-8f76ff76-b6d5-4b5f-bb58-421b485588f6.png)

You mean you also want different color for the confidence interval and point estimation as well? You can't do it now, but I can try to implement something to do that. This will take a long time.

**Comment by nicholekulikowski** [comment]
It works perfectly, thank you so much!

**Comment by adayim** [comment]
Glad to hear, just want to mention that the parameter should be set to which="ci" in the CRAN version.

**Comment by adayim** [comment]
Yeah, you can do that by changing `ci_fill`.
