### ISSUE TITLE
double zero 

### ISSUE THREAD

**Issue by zhui126** [adayim/forestploter#21]
Double zeros in the x-ticks were found in the plot after updated for 0.1.9 and 0.2.0 version.

And when you set   ticks_at = c(-0.1, -0.05, 0, 0.05, 0.1, 0.15), some of the ticks like 0.05 will be missing from the plot.

**Comment by adayim** [comment]
Please read the manual of `forest` function, and set `ticks_digits=2` to keep the digits.

**Comment by adayim** [comment]
Fixed, now the`forest` will change the `ticks_digits` based on `ticks_at` 75ad57fa986f8e348d4a5a448bba96777c1c7fb4
