### ISSUE TITLE
difference color for point estimate and confidence interval

### ISSUE THREAD

**Issue by bioljlin** [adayim/forestploter#22]
Hi there! I was wandering if it is possible to define difference colors for point estimates and confidence intervals (like blue for point estimate and black for confidence interval)?

**Comment by bioljlin** [comment]
Thanks for your reply. It seems to change the color of both confidence of interval and point estimate. I would like to show difference color for point estimate, as shown in the screen shot below(black color for the line of confidence interval and blue color for the box of point estimate).




Many thanks and best regards,
LJ
---- Replied Message ----
| From | Alim ***@***.***> |
| Date | 10/6/2022 01:27 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [adayim/forestploter] difference color for point estimate and confidence interval (Issue #22) |

Yes, you can. Please check the vignette here. Use edit_plot to change it.

g<- edit_plot(g,
               row= c(3, 6, 11, 13),
               col=4,
               which="ci",
               gp= gpar(col="green"))

**Comment by bioljlin** [comment]
Thanks for your reply. It seems to change the color of both confidence of interval and point estimate. I would like to show difference color for point estimate, as shown in the screen shot below(black color for the line of confidence interval and blue color for the box of point estimate).

![BF7F9CA1-DCFB-49C6-BB83-914A86D679A4](https://user-images.githubusercontent.com/86034226/194259029-06a2d6d5-d737-4ec4-aa4d-73547ad6aa89.png)

**Comment by adayim** [comment]
Thank you for reporting this, you can change the color by setting `ci_fill` in the `forest_theme` function. Please let me know if the changes works for you. And try to edit the plot see if the changes working. Thank you.

**Comment by gpessoaamorim** [comment]
This is really helpful. One other feature that would be of great value would be to present CIs on top of the boxes for groups where the CI is smaller than the box (and with a different colour) as is standard practice now

**Comment by gpessoaamorim** [comment]
> 

This works well but is not transferring to the legend (see snippet)

![image](https://user-images.githubusercontent.com/59774594/200887864-079640f9-a3f2-4174-8dfd-715f83d4596e.png)

**Comment by adayim** [comment]
Hi, can you paste your code here? I am not sure how you got this figure. I can have a look and make some changes. 

The change will not be applied to legend if you changed the color of the CI with `edit_plot` function. I will need to think about this if this is how you did it, this may take a while and I am a bit busy for now.

**Comment by gpessoaamorim** [comment]
Thanks for looking into this. I've installed the dev version but still not working

This is what my code looks like:

`
forest_plot_mortality<-forest(
  forest_plot_table[,c(1:7,11:13)],

        est=list(
        forest_plot_table$`Mortality (RECOVERY crude)`,
         forest_plot_table$`Mortality (RECOVERY adjusted)`,
         forest_plot_table$`Mortality (Reference population)`),
  
lower=list(forest_plot_table$`lower_bound_95CI_RECOVERY (crude)`,
           forest_plot_table$`lower_bound_95CI_RECOVERY (adjusted)`,
           forest_plot_table$`lower_bound_95CI_Reference population`
),

upper=list(forest_plot_table$`upper_bound_95CI_RECOVERY (crude)`,
           forest_plot_table$`upper_bound_95CI_RECOVERY (adjusted)`,
           forest_plot_table$`upper_bound_95CI_Reference population`
),

sizes=list(1/forest_plot_table$`Variance (RECOVERY crude)`/10,
           1/forest_plot_table$`Variance (RECOVERY adjusted)`/10,
           1/forest_plot_table$`Variance (Reference population)`/10),

ci_column = 7,
xlim=c(0,35),
xlab = "Mortality (%)",
ref_line = 0,
nudge_y=0.3,
theme = forest_theme(
  ci_col="black",
                    ci_fill =colors,
                     ci_alpha=0.9,
                     legend_name="Cohort",
                     ci_pch=15,
                     ci_Theight = 0.2,
                     legend_position="bottom",
                     base_family = "Mulish",
                     legend_value=c("RECOVERY (crude)",
                                    "RECOVERY (adjusted)",
                                    "Reference population")))%>%
  insert_text(.,
              text = "Mortality (95% CI)",
              col = 8:10,
              part = "header",
              gp = gpar(fontface = "bold"))%>%
  edit_plot(row=10,
            which="text",
            gp=gpar(fontface="bold"
                    ))`

**Comment by gpessoaamorim** [comment]
Thanks – that absolutely solved the issue!
