### ISSUE TITLE
Axis labels for X-axis not displaying

### ISSUE THREAD

**Issue by MCSuciu** [adayim/forestploter#23]
Hi, 
in certain instances of plotting, with custom x-ticks, the x-axis is not displaying. I tried altering the axis range without any luck. It seems to be happening when I choose axes limits with decimals.

Example code:

min_tick_custom <- -0.05
max_tick_custom <- 0.02
center_tick <- 0

p_qt <- forestploter::forest(cbind(dat[,c("Area","Phenotype","Cohorts", "Cases")], 
                                    ` `=paste(rep(" ", 1), collapse = " "),
                                    ` `=paste(rep(" ", 18), collapse = " "),
                                   dat[,c("Effect (95% CI)", "Pval", "AAF")]),
                              est = dat$Effect,
                              lower = dat$LCI_Effect, 
                              upper = dat$UCI_Effect,
                              ci_column = c(6),
                              ref_line = center_tick,
                              xlim = c(min_tick_custom_qt,max_tick_custom_qt),
                              ticks_at = c(min_tick_custom, center_tic,max_tick_custom),
                              footnote=unique(plot_name),
                              theme=forestploter::forest_theme(base_size = 10,
                                                               base_family = 'sans',
                                                               ci_col = c("black"),
                                                               ci_pch = 16,
                                                               ci_Theight = 0.3,
                                                               xaxis_cex=0.8,
                                                               refline_col='red',
                                                               footnote_col = "#636363",
                                                               footnote_fontface = "italic"))

plot(p_qt)

**Comment by adayim** [comment]
Hi, it's seems to me that you have very small x-axis values. Have you tried to change the `ticks_digits` to keep more digits? The default is to keep 1 digits only.

**Comment by adayim** [comment]
Fixed, now the`forest` will change the `ticks_digits` based on `ticks_at` 75ad57fa986f8e348d4a5a448bba96777c1c7fb4
