### ISSUE TITLE
How can I add a line on the top of header.

### ISSUE THREAD

**Issue by lizhiwei1994** [adayim/forestploter#24]
Firstly, thanks for your dedication in forest plot with r.

**Context**

I plot a forestplot and want to add three line to make the figure looks like a three-line table.

I can add two lines by using `add_underline()`.

**Question**

How can I add a line on the top of header.

**Reproducible code**

```
library(forestploter)
dt <- read.csv(system.file("extdata", "example_data.csv", package = "forestploter"))
dt <- dt[1:6,1:6]

dt$` ` <- paste(rep(" ", 20), collapse = " ")

p <- forest(dt[,c(1:3, 7)],
            est = dt$est,
            lower = dt$low,
            upper = dt$hi,
            ci_column = 4)

g <- add_underline(p, part = 'header')
g <- add_underline(g, row = 6, part = 'body')

g
```
The current picture looks like this. It is missing a line on the top side of the header.

![image](https://user-images.githubusercontent.com/59855957/196155844-2caab959-f3be-4b01-a7e8-626a798da49e.png)

**Comment by adayim** [comment]
Emm, sorry. As suggested by the function name, `add_underline` only supports adding underline not topline. Is it necessary to add a topline? The forestplot looks like a table but it's not a statistical table after all. I don't see any need for this.

**Comment by lizhiwei1994** [comment]
Sorry for late reply. I just saw a forestplot in a [paper](https://doi.org/10.1186/s12940-018-0429-3) and I want to replot it. I have done this with `forestplot` package, but it would be better if `forestploter` can also do this.

![image](https://user-images.githubusercontent.com/59855957/196843838-178d3a9d-c024-4c72-b54f-331b755070c6.png)
