### ISSUE TITLE
How to handle missing confidence intervals?

### ISSUE THREAD

**Issue by xuewei01** [adayim/forestploter#26]
For datasets with missing values (i.e. NA) in the low and high confidence intervals, the package reports error. Is there a way to handle such missing low or high bounds for plotting? Thanks!

**Comment by adayim** [comment]
Hi, the easiest way would be set est to NA as well. But I have updated the package and it will throw a warning now.

**Comment by xuewei01** [comment]
Thanks for your quick response. Here is a simple example with three
estimates and each has the confidence interval:
estimate, low_ci, high_ci
4.67, 1.87,  5.98
5.42, 3.42, NA
3.65, 2.1, 4.63

As you can see, all the estimates are not NA. I like to visualize them on a
forest plot with three rows. For the second row without upper limit, is it
possible to just show the other half (from lower limit to estimate)? Any
suggestions will be very appreciated.

**Comment by adayim** [comment]
I don't think it's a good idea to show half of the CI. It's meaningless. I would suggest you use different method to derive your CI, bootstrap maybe.
