### ISSUE TITLE
How to use subscript in header?

### ISSUE THREAD

**Issue by lizhiwei1994** [adayim/forestploter#27]
**Context**

Hi, adayim. I want to show PM<sub>2.5</sub> in the header.

I have tried some syntax such as `$PM_{2.5}$` , `$PM~2.5~$` and `expression('PM'[2.5])`, but all faild.

**Question**

How can I use subscript in header with forestploter?

**Reproducible code**

```
library(forestploter)
dt <- read.csv(system.file("extdata", "example_data.csv", package = "forestploter"))
dt <- dt[1:6,1:6]

dt$`$PM_{2.5}$` <- paste(rep(" ", 20), collapse = " ")
# dt$`$PM~2.5~$` <- paste(rep(" ", 20), collapse = " ")
# dt$`expression('PM'[2.5])` <- paste(rep(" ", 20), collapse = " ")

p <- forest(dt[,c(1:3, 7)],
            est = dt$est,
            lower = dt$low,
            upper = dt$hi,
            ci_column = 4)
p
```

![image](https://user-images.githubusercontent.com/59855957/196847172-b1631b84-397f-4e48-86d2-694c2f304362.png)

**Comment by adayim** [comment]
Please refer to the document [here](https://cran.r-project.org/web/packages/gridExtra/vignettes/tableGrob.html)
