### ISSUE TITLE
Is there any way to add superscript to the header text?

### ISSUE THREAD

**Issue by Guiquan-27** [adayim/forestploter#29]
Hi there,

Thank you for your great work on forest plot. I am wondering if it's possible to add superscript to the header text and make some text to be italic and others keeping unchanged, which is really important for publication. Such as "_P_ value<sup>a<sup>". 

Thank you very much!

**Comment by adayim** [comment]
Please check out this issue #27

**Comment by Guiquan-27** [comment]
> Please check out this issue #27
It did work! Thank you very very much!!!!
