### ISSUE TITLE
Extend functionality for multiple plot columns

### ISSUE THREAD

**Issue by srhaup2** [adayim/forestploter#31]
First off, thank you for making this package. This is the best forest plot package I've come across by far and it has excellent functionality and customizability. I have a couple of questions/requests regarding making plots with multiple plot columns. 

**Different ticks_digits for different plot columns**

I believe earlier versions of this package supported users passing a vector to the ticks_digits parameter if they wished to have this parameter vary across different plot columns. I think having this feature could be useful if the two plot column estimates are on very different scales. Now when a vector is passed, you get the following error:

```
Error in if (ticks_digits == 1L & !is.null(ticks_at)) { : 
  the condition has length > 1
```

stemming from line 121 of `forest.R`

**Vary theme parameters across plot columns**

I also think it would be useful to vary theme parameter such as ci_pch, ci_col across plot columns. Currently, if you provide two estimate vectors and specify two plot columns, then you cannot adjust the theme to, for example, make confidence intervals from plot column 1 green, and those in plot column 2 red (i.e. `ci_col = c("green", "red")`. I don't believe any of the theme parameters support this type of input actually. It seems that this is because with two estimate vectors and two plot columns, the package determines there to be only one "group."

**Comment by adayim** [comment]
Thanks for those suggestions. I was thinking all columns should have the same `ticks_digits`, but obviously not. I will change it back in the next version, I hope it won't be too long. 
I am not sure if I am going to implement this, as this will complicate the error checking. You can also use `edit_plot` to achieve it. I will think about it.

**Comment by adayim** [comment]
I have fixed the issues with `ticks_digits` now. Can you try it out? You need to install it from GitHub. 
For vary theme parameters across plot columns, you can use `edit_plot ` to edit the color.

**Comment by srhaup2** [comment]
This works just how I would like it to now. Thanks!

RE: using `edit_plot` to vary theme parameters -- got it. I'll use this method. 

Thanks again!
