### ISSUE TITLE
X axis break

### ISSUE THREAD

**Issue by huihui2333333** [adayim/forestploter#32]
Hi, thanks for providing this excellent package, which works very well. I have a problem. I have get some results which were ranged from 2 to 20 and I didn't find the method for x axis breaking. For example, I wanner make a gap between 5 to 15, so that I can show all results in one graph. Could you help me to complish it? Thanks so much!

**Comment by adayim** [comment]
Hi, I don't think I understand what you mean. Can you please give an example? Do mean you have value ranging from 2 to 20 and you want to show data from 5 to 15, is that right? Or do you want to have ticks at 5 and 15? 
Use `xlim` to define the limits of the x-axis, and `ticks_at` to define where you want to show the ticks.
