### ISSUE TITLE
Multiple CIs in one cell

### ISSUE THREAD

**Issue by Kexin-xu-01** [adayim/forestploter#33]
Hello!

I would like to plot multiple CIs on top of each other in the same cell (i.e. same column), represented by different colours & shown in legends.

I am currently aiming for 5 CIs, so I wrote something like this:
tm <- forest_theme(base_size = 10,
                   refline_col = "red",
                   legend_name = "5 groups",
                   legend_value = c(1:5)) # I want to plot 5 groups

p <- forest(dt[,c(2,22)],
            est = list(dt$est_gp1,
                       dt$est_gp2,
                       dt$est_gp3,
                       dt$est_gp4, 
                       dt$est_gp5),
            lower = list(dt$low_gp1,
                         dt$low_gp2,
                         dt$low_gp3,
                         dt$low_gp4,
                         dt$low_gp5), 
            upper = list(dt$hi_gp1,
                         dt$hi_gp2,
                         dt$hi_gp3,
                         dt$hi_gp4,
                         dt$hi_gp5),
            ci_column = c(3), # because I want them all in the same column
            ref_line = 1,
            theme = tm)

However, there was a bug which made some CIs misaligned with the rows (see picture: from "hypertension" in row 6). I have double-checked and I can confirm that the dataframe used for plotting is correctly aligned.

Also, do you know how to add p-values as asterisks to the plot please?

I am trying to make a plot like this.

Thanks!
![Screenshot 2023-01-30 at 19 45 46](https://user-images.githubusercontent.com/123656247/215579899-0e6d0204-d73d-49a8-aba8-bb823e8f49ea.png)
<img width="408" alt="Screenshot 2023-01-30 at 20 33 52" src="https://user-images.githubusercontent.com/123656247/215588976-4d27d0fe-98a8-4c29-a21f-e3e283023e14.png">

**Comment by adayim** [comment]
I don't know what you mean by misaligned. You didn't provide any reproducable data to show me. I used the package data and it worked perfectly fine.
```r
dt <- read.csv(system.file("extdata", "example_data.csv", package = "forestploter"))
dt$` ` <- paste(rep(" ", 20), collapse = " ")
dt <- dt[1:10, ]

tm <- forest_theme(base_size = 10,
                   refline_col = "red",
                   legend_name = "5 groups",
                   legend_value = c(1:5)) # I want to plot 5 groups

p <- forest(dt[,c(1, 19)],
            est = list(dt$est_gp1,
                       dt$est_gp2,
                       dt$est_gp3,
                       dt$est_gp4,
                       dt$est),
            lower = list(dt$low_gp1,
                         dt$low_gp2,
                         dt$low_gp3,
                         dt$low_gp4,
                         dt$low),
            upper = list(dt$hi_gp1,
                         dt$hi_gp2,
                         dt$hi_gp3,
                         dt$hi_gp4,
                         dt$hi),
            ci_column = 2, 
            ref_line = 1,
            theme = tm)

p
```

And where do you want to have p-values as asterisks? Would you please state your problem clearly?

**Comment by Kexin-xu-01** [comment]
Hello! Thank you very much for your very kind answer! I have solved the alignment issue. I would like the pvalue to be added as asterisks to the right of each CI plot (i.e. as *, **, ***). Do you think that would be possible?

Thank you!

**Comment by adayim** [comment]
Right of CI plot? You mean right hand side of the CI plot? NO, but you can add a new column at the right-hand side and use asterisks as content of the column.

**Comment by Kexin-xu-01** [comment]
Thank you! Is it possible to have 5 asterisks per row, corresponding to the 5 different groups? How should I specify this in the code? Thank you again!

**Comment by adayim** [comment]
Yes, you can use line break between asterisks.

**Comment by Kexin-xu-01** [comment]
Thank you! I have another question. Do you know how to adjust the width of each column? In the first column, some of my texts are too long so they are hidden. I noticed a similar issue in the example plot too. Thank you!
![Uploading Screenshot 2023-01-31 at 22.03.19.png…]()

**Comment by adayim** [comment]
Sorry, I don't see your plot. The width of the column is determined by the text in the table. I think this was already written in the readme and vignettes. You can also use line break.

**Comment by Kexin-xu-01** [comment]
![Screenshot 2023-01-31 at 22 03 19](https://user-images.githubusercontent.com/123656247/216026033-936ba6c5-65d6-4143-8159-ec3343e75ad6.png)
Sorry, I have reattached the image. As you can see, sometimes the column width is smaller than text, resulting in some of the text being cut off. 
<img width="524" alt="Screenshot 2023-02-01 at 11 07 02" src="https://user-images.githubusercontent.com/123656247/216026338-02078556-7f28-4ae1-8644-93cfab946558.png">

I have tried the linebreak, but this makes the row twice as thick as other row. Since I have 5 groups of CI, the row is already very thick. Is there a way to shrink the row thickness for the rows that don't have any CI plot (i.e.. the subheading rows)?

I am very sorry for all these questions.

**Comment by adayim** [comment]
Leave that row blank and use `add_text()` to add the long text.

**Comment by Kexin-xu-01** [comment]
Hello! Sorry for keeping bothering you! I tried add_text, but because the column width didn't increase, the text occupied some of the neighbouring column too and started overlapping with neighbouring text. Is there a way to increase the column width manually?

**Comment by Kexin-xu-01** [comment]
Thank you very much for your kind edits!

With clip = FALSE, the words are showing but they are overlapping with the following column, since the column width didn't increase. 
<img width="599" alt="Screenshot 2023-02-02 at 23 50 38" src="https://user-images.githubusercontent.com/123656247/216477628-6e0f6a93-b4b3-49f4-8aa1-23456c92eef4.png">

With clip = TRUE, the end of the words were cut off like before 
<img width="583" alt="Screenshot 2023-02-02 at 23 52 46" src="https://user-images.githubusercontent.com/123656247/216477697-546d8b69-6334-45b9-9c44-e084f9bd7c10.png">

**Comment by adayim** [comment]
As I have explained before, the width of the text will be increased if you bold text later. I would suggest you add some space after the longest text so you will have extra space. Use `paste` to add some blank space to the text for example.

**Comment by Kexin-xu-01** [comment]
It worked! Thank you so much for your kind help!
