### ISSUE TITLE
Sizes option

### ISSUE THREAD

**Issue by kaitlinmayne** [adayim/forestploter#34]
Hi, thanks for this really useful package, I'm still quite new to R so please forgive me if this is simpler than I've realised...
I'd be really grateful for your advice on how to manipulate the sizes argument beyond the suggested eg. sizes=0.4 or sizes = data$se in the documentation.
I've created a forest plot for a subgroup analysis and want to scale the squares to the number of participants within each subgroup, for each subgroup, rather than across the whole plot
I've tried using sizes=data$total_participants where total_participants is the number of participants for each plotted estimate, I've tried using sizes=data$proportion where proportion is the % of participants for that category of the subgroup
I've also tried a more manual approach using a vector eg. sizes=c(0.63,0.31....) and in different forms *100 etc

The format of the data I'm using to create the plot is attached 
![image](https://user-images.githubusercontent.com/125603501/220087312-76c119d8-3c58-4bf0-becc-c256eb920226.png)

And the code I'm using:

forest(data[,c(1:3, 9:11)],
       est = data$hr,
       lower = data$lower, 
       upper = data$upper,
       sizes=data$total_participants,
       ci_column = 4,
       xlim = c(0, 3),
       ticks_at = c(0,1,2,3),
       ref_line = 1.0,
       is_summary = c(FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,
                      FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,
                      FALSE,FALSE,FALSE,FALSE,FALSE,TRUE),
       vert_line = 0.91,
       theme=my_theme)

Thank you, very grateful for any help!

**Comment by adayim** [comment]
Hi, I think you need to find a way to calculate weight. Sorry, I can't help you to define the calculation of the weight. The size is used to reflect the uncertainty around the point estimation.
