### ISSUE TITLE
Sizes no longer accepting a numeric vector

### ISSUE THREAD

**Issue by hanchamb** [adayim/forestploter#35]
Hello,

Thanks so much for making this package, it has been very helpful to me! I have been using it over the past couple of months and have recently started using the sizes variable in forest(), similarly to how the guide recommends, with dt$se for example. 
However, today it has stopped accepting that, for instance if sizes was initially a vector such as c(1, NA, 0.17, 0.72), on the forest plot only the first dt$est value is scaled to the correct size, but all other dt$est values have disappeared from the plot completely, leaving just the confidence interval! This is new and yesterday all dt$est values on the forest plot were scaled by the appropriate amounts.
I updated all my packages on RStudio today but as far as I'm aware that's the only change I've made. I'm not very experienced with R so apologies if it is something basic, I just can't explain it!
The dt$est values return if I comment out the whole of the sizes variale, and are still there if I specify sizes to be a single value.

Thanks in advance!

**Comment by adayim** [comment]
Hi, the sizes will not be scaled anymore. It will use the value you have provided as it is. Maybe you can scale the size or multiply by some value? 
It used to use the following to scale the size:
```r
x <- sqrt(1/sizes)
sizes <- x/max(x)
```

Can you try to run the example and let me know if it works? It works fine on my side.

**Comment by hanchamb** [comment]
Hi, thanks for your reply. The example above did not work but I perhaps haven't stated myself clearly. In forest() my code used to work for sizes = c(1,NA,0.5, 0.5), but it now acts on the forest plot as if this as c(1,NA,0,0) (i.e. the markers for the 3rd and 4th CI are gone). I tried the example you gave above but it still behaved the same. If all given the same value, i.e. sizes = 1, it is fine and the markers exist for the 3rd and 4th row, but I don't know why c(1,NA, 0.5, 0.4) is not working when it was before I updated

**Comment by adayim** [comment]
Hi, you don't have any example data or output for me to check. But I have created a few data points. It works, I have no idea why it is not working in your case.
```r

# Read provided sample example data
est <- runif(4, -1, 1)
est[2] <- NA
low <- est - 1.96*c(1, NA, 0.5, 0.4)
up <- est + 1.96*c(1, NA, 0.5, 0.4)

dt <- data.frame(gp = c("Total", "", "Var1", "Var2"),
                 ci = paste(rep(" ", 20), collapse = " "))

p <- forest(dt,
            est = est,
            lower = low,
            upper = up,
            sizes = c(1, NA, 0.5, 0.4),
            ci_column = 2)
p
```

![rplot](https://user-images.githubusercontent.com/5401293/220963204-d819349a-ed5b-43e6-8100-9ea972ac17e5.png)

**Comment by hanchamb** [comment]
Hello, thanks so much again. Yes sorry they're large datasets so I couldn't share data but thanks so much for giving an example. I will try and investigate why it is not working for me suddenly but I'm glad it is probably not due to me updating other packages and them conflicting. Thanks so much for your help! :)
