### ISSUE TITLE
Is it possible to overlap forest plots (plotting two sets of variables within a single column)

### ISSUE THREAD

**Issue by TACdeVries** [adayim/forestploter#36]
I am performing a meta-analysis using a meta-analytic method that allows for the inclusion of different combinations of values. One of such combinations is the median with min, Q1, Q3, and max values of a single distribution. I would have hoped to present those values graphically within a single column of the forest plot. 

Is this within the range of possibilities? I was aiming for something along the lines of this (https://www.metafor-project.org/doku.php/plots:forest_plot_with_multiple_cis), but the metafor package is by not flexible enough for my other purposes (e.g., presenting two forest plots within a single figure). 

Below a picture of what I am aiming for:
![image](https://user-images.githubusercontent.com/126504479/221635281-579adb47-b6da-4ed4-88ca-4dd663924017.png)

I’ve tried playing around with the est, lower, upper, and ci_column variables, but I keep getting error messages. If I change the column identifier of one of the two overlapping variables sets to a non-forest plot column, I am able to plot three forest plots within a single plot, however. 

Any ideas? 

Kind regards,
Tim

**Comment by TACdeVries** [comment]
Hi Adayim,

I have no experience whatsoever with making packages myself. If the underlying code of the packages used by forestploter do not allow for overlap within cells, I also don't have a direct suggestion to get this working. One way, albeit a rather 'hacky' solution, is to overlap two forestploter objects.

This is what I did this morning using the steps mentioned in the section on 'Plot insets' on ([Laying out multiple plots on a page](https://cran.r-project.org/web/packages/egg/vignettes/Ecosystem.html)). Below the final line of code used. 

Thus, I first made a standard scatterplot which I gave the standard void theme (removes near-everything) and then added the two plots to this canvas using the annotation_custom function. By fitting both plots to the entirety of the scatterplot they overlapped near-perfectly. 

```
ggplot(x=1:10, y=1:10) + theme_void() + annotation_custom(grob = p2, xmin = -Inf, xmax = Inf, ymin = -Inf, ymax = Inf) + annotation_custom(grob = p, xmin = -Inf, xmax = Inf, ymin = -Inf, ymax = Inf)
```

Note, that I was forced to include all changes that I made manually (e.g., insert_text(...)) to both plots to ensure the width of each cell in the tables was the same. I gave the first plot a transparent and the second a white/greyish background. All the text and lines in the second plot were made transparent to avoid a 'bold' like effect.  

Yet the only two parameters I was unable to make transparant were the x-axis tick labels, and the colour of the x-axis line. Do you know if this is possible? It is only a very minor detail but the tick labels look somewhat bolder than the other text, e.g., see the '100' label on the x-axis in the picture below. 

![image](https://user-images.githubusercontent.com/126504479/222115327-7b789bf0-cfd5-4e0f-8d30-2ccc87e37b39.png)

Here is a preview of a cropped version of the first drafted plot with two ranges in a single column. 

![image](https://user-images.githubusercontent.com/126504479/222113005-4faf37cf-51eb-4ad3-8511-5e4e609fa1c7.png)

All in all, I think this works quite well with the major downside of A LOT of extra lines of code. To make this easier in the future and for other users, I will therefore still pulled a request, I hope that's OK.

Thank you so much for your time,
Tim

**Comment by adayim** [comment]
Hi Tim,

Can you try out the development version of the package? You can install the development version with the following:
```r
devtools::install_github("adayim/forestploter@dev")
```

In this version, you can specify a custom CI function to draw the whisker. I have written a new function `make_boxplot` to draw a boxplot. Try the following example:
```r
library(grid)
library(forestploter)
# Function to calculate Box plot values
box_func <- function(x){
  iqr <- IQR(x)
  q3 <- quantile(x, probs = c(0.25, 0.5, 0.75), names = FALSE)
  c("min" = q3[1] - 1.5*iqr, "q1" = q3[1], "med" = q3[2],
    "q3" = q3[3], "max" = q3[3] + 1.5*iqr)
}
# Prepare data
val <- split(ToothGrowth$len, list(ToothGrowth$supp, ToothGrowth$dose))
val <- lapply(val, box_func)

dat <- do.call(rbind, val)
dat <- data.frame(Dose = row.names(dat),
                  dat, row.names = NULL)

dat$Box <- paste(rep(" ", 20), collapse = " ")

# Draw single group box plot
tm <- forest_theme(ci_Theight = 0.2)

p <- forest(dat[,c(1, 7)],
            est = dat$med,
            lower = dat$min,
            upper = dat$max,
            # sizes = sizes,
            fn_ci = make_boxplot,
            ci_column = 2,
            lowhinge = dat$q1,
            uphinge = dat$q3,
            hinge_height = 0.2,
            index_var = c("lowhinge", "uphinge"),
            gp_box = gpar(fill = "black", alpha = 0.4),
            theme = tm
)
p

# Multiple group
# Prepare data
dat_oj <- dat[c(1, 3, 5),]
dat_vc <- dat[c(2, 4, 6), ]

dat <- data.frame(Dpse = c(0.5, 1, 2))
dat$Box <- paste(rep(" ", 20), collapse = " ")

# Draw plot
tm <- forest_theme(ci_Theight = 0.2,
                   ci_pch = 3)

p <- forest(dat,
            est = list(dat_oj$med, dat_vc$med),
            lower = list(dat_oj$min, dat_vc$min),
            upper = list(dat_oj$max, dat_vc$max),
            fn_ci = make_boxplot,
            ci_column = 2,
            lowhinge = list(dat_oj$q1, dat_vc$q1),
            uphinge = list(dat_oj$q3, dat_vc$q3),
            hinge_height = 0.2,
            index_var = c("lowhinge", "uphinge"),
            theme = tm
)

p
```

Please let me know if this is what you are expecting.

**Comment by TACdeVries** [comment]
Hi Adayim,

Yes, this works well! 

Is there a way to get this working with summary estimates, too? I tried to put all findings within one forest plot (so not overlapping plots) by using ifelse functions. 

This way the outer whisker is used for the max/max values if available, and the p25/75 if unavailable. The min/max values were also used for the second forest plot on the median level with its 95% CI per study and the pooled estimate. For the medians, the min were the lower bound of the confidence intervals and the max the upper bound.

However, I keep getting errors when using the 'is_summary' variable. Not sure why this is. 

```
p <- forest(dat,
            est = list(df$med, df$med),
            lower = list(df$min, df$lower),
            upper = list(df$max, df$upper),
            fn_ci = make_boxplot,
            ci_column = c(2, 4),
            lowhinge = list(df$q1, rep(F, nrow(df)),
            uphinge = list(df$q3, rep(F, nrow(df))),
            hinge_height = 0.2,
            index_args= c("lowhinge", "uphinge"),
            is_summary=c(rep(F, nrow(df)-3), T, F, F),
            theme = tm
)
```

Another option is to keep using overlapping plots, which still works well. I'd then use the make_boxplot function for studies reporting sufficient information and the standard function for any other studies. 

Best,
Tim

**Comment by TACdeVries** [comment]
Hi Adayim,

Sure, please find below a reproduceable example.

```ruby
test.Mean <- c(50, 30, NA, NA, NA, NA, NA, NA)
test.SD <- c(20, 10, NA, NA, NA, NA, NA, NA)
test.Min <- c(NA, NA, 10, 5, NA, NA, 5, NA)
test.P25 <- c(NA, NA, 30, 30, 50, 70, NA, NA)
test.P50 <- c(NA, NA, 80, 80, 80, 80, 80, NA)
test.P75 <- c(NA, NA, 110, 100, 100, 100, NA, NA)
test.Max <- c(NA, NA, 250, 150, NA, NA, 310, NA)

test.crude <- cbind(test.Mean, test.SD, test.Min, test.P25, test.P50, test.P75, test.Max)

#note, last set of values = for summary estimate
test.Med <- c(50, 20, 80, 80, 80, 80, 80, 75) 
test.lb.CI <- c(45, 15, 75, 75, 75, 75, 75, 70) 
test.ub.CI <- c(55, 25, 85, 85, 85, 85, 85, 80) 

test.meta <- cbind(test.Med, test.lb.CI, test.ub.CI) 

test.df <- cbind(test.crude, test.meta) |> as.data.frame()
test.df$Box <- paste(rep(" ", 20), collapse = " ")
test.df$Box2 <- paste(rep(" ", 20), collapse = " ")
```

My apologies for the ifelse functions. I could first create a new variable outside of the forest function to make it little easier to digest, but the result is the same. Note that I used the P50 as the lower and upper limit for studies reporting only a P25, P75, and median to ascertain that their P25 and P75 values were still used in the lowhinge and uphinge functions. 

The syntax below is without a summary function for the last set of values in the dataframe. 
```ruby
p1 <- forestploter::forest(test.df[ , 11:12],
est=list(ifelse(!is.na(test.df$test.Mean), test.df$test.Mean, test.df$test.P50), test.df$test.Med),
lower=list(ifelse(!is.na(test.df$test.Mean), test.df$test.Mean-test.df$test.SD, ifelse(!is.na(test.df$test.Min), test.df$test.Min, test.df$test.P50)), test.df$test.lb.CI),
upper=list(ifelse(!is.na(test.df$test.Mean), test.df$test.Mean+test.df$test.SD, ifelse(!is.na(test.df$test.Max), test.df$test.Max, test.df$test.P50)), test.df$test.ub.CI),
sizes=0.75,
fn_ci = make_boxplot,
ci_column = c(1, 2), 
lowhinge = list(ifelse(!is.na(test.df$test.P25), test.df$test.P25, F), rep(F, nrow(test.df))),
uphinge = list(ifelse(!is.na(test.df$test.P25), test.df$test.P75, F), rep(F, nrow(test.df))),
hinge_height = 0.2,
index_args= c("lowhinge", "uphinge"),
#is_summary=c(rep(F, nrow(test.df)-1), T),
theme=tm)

p1
```

Below is with the summary function included which produces the following error: 'Error in (function (est, lower, upper, sizes = 1, gp, xlim): unused arguments (lowhinge = FALSE, uphinge = FALSE, hinge_height = 0.2)'.

```ruby
p1 <- forestploter::forest(test.df[ , 11:12],
est=list(ifelse(!is.na(test.df$test.Mean), test.df$test.Mean, test.df$test.P50), test.df$test.Med),
lower=list(ifelse(!is.na(test.df$test.Mean), test.df$test.Mean-test.df$test.SD, ifelse(!is.na(test.df$test.Min), test.df$test.Min, test.df$test.P50)), test.df$test.lb.CI),
upper=list(ifelse(!is.na(test.df$test.Mean), test.df$test.Mean+test.df$test.SD, ifelse(!is.na(test.df$test.Max), test.df$test.Max, test.df$test.P50)), test.df$test.ub.CI),
sizes=0.75,
fn_ci = make_boxplot,
ci_column = c(1, 2), 
lowhinge = list(ifelse(!is.na(test.df$test.P25), test.df$test.P25, F), rep(F, nrow(test.df))),
uphinge = list(ifelse(!is.na(test.df$test.P25), test.df$test.P75, F), rep(F, nrow(test.df))),
hinge_height = 0.2,
index_args= c("lowhinge", "uphinge"),
is_summary=c(rep(F, nrow(test.df)-1), T),
theme=tm)

p1
```

**Comment by TACdeVries** [comment]
Hi Adayim,

Another issue related to this (but lease let me know if you want me to open a different thread for this) is that the location of the lower and the upper hinge seem to be incorrect. 

See below a reproducible example with the same dataset as before. Instead of using the median value for studies reporting a median with P25-P75 to plot the min/max range, this time I used the P25/P75. The locations of the hinges do not match those created by the min/max. The min/max locations seem to be the correct ones (see picture). 

```ruby
p1 <- forestploter::forest(test.df[ , 11:12],
est=list(ifelse(!is.na(test.df$test.Mean), test.df$test.Mean, test.df$test.P50), test.df$test.Med),
lower=list(ifelse(!is.na(test.df$test.Mean), test.df$test.Mean-test.df$test.SD, ifelse(!is.na(test.df$test.Min), test.df$test.Min, test.df$test.P25)), test.df$test.lb.CI),
upper=list(ifelse(!is.na(test.df$test.Mean), test.df$test.Mean+test.df$test.SD, ifelse(!is.na(test.df$test.Max), test.df$test.Max, test.df$test.P75)), test.df$test.ub.CI),
sizes=0.75,
fn_ci = make_boxplot,
ci_column = c(1, 2), 
lowhinge = list(ifelse(!is.na(test.df$test.P25), test.df$test.P25, F), rep(F, nrow(test.df))),
uphinge = list(ifelse(!is.na(test.df$test.P75), test.df$test.P75, F), rep(F, nrow(test.df))),
hinge_height = 0.2,
index_args= c("lowhinge", "uphinge"),
#is_summary=c(rep(F, nrow(test.df)-1), T),
theme=tm)

p1
```

![image](https://user-images.githubusercontent.com/126504479/223489004-3f28c01c-428c-43e5-beed-32253cc09fcb.png)

**Comment by adayim** [comment]
Hi Tim,

Thank you for checking this. I have fixed both issues you are having now. Would you please retry it again? You need to pass `NA` instead of `F` if you want the second column to draw standard whisker. Thank you very much.

**Comment by TACdeVries** [comment]
Hi Adayim,

Thank you so much. The issues have been resolved and the plots are starting to look terrific! See below the current version of the plot with the above datapoints.

![image](https://user-images.githubusercontent.com/126504479/223679671-cfac079e-6163-4a20-9a72-dd8285930d8b.png)

Thanks again for all your help!

Best,
Tim

**Comment by adayim** [comment]
Great, glad to hear it works as expected.

**Comment by Estherlx** [comment]
Hi Adayim,

I am drawing a forest plot for agreement coefficients and 95% CI. The range is 0-1. I find the plot area is too narrow. The x-ticks labels are covering each other. Do you know how to make the plot area wider. The graph is attached here. Thanks.

Best regards,
Esther
![forestplot_v1](https://user-images.githubusercontent.com/32938426/224170073-5925dbbd-67ef-44f2-baae-6fdef1366de0.png)

**Comment by adayim** [comment]
Please checkout the vignettes of the package. Width of the box to draw the CI is determined by the width of column. Increase the number of space in the column to give more space to draw CI. 

https://cran.r-project.org/web/packages/forestploter/vignettes/forestploter-intro.html#simple-forest-plot

**Comment by Estherlx** [comment]
Hi Adayim,

Thank you for your reply. Yes. I tried to find any argument control width of column. But I did not find 'ci_width' in command 'forest_theme' and 'forest'. Can you please tell me which argument I should use? My code is as below. Besides, do you know how to adjust the forest plot to fit the whole plotting area? Thanks. 

Esther

dd<-pair_gwet2_num %>% mutate(variable=c('PIQUAL score','PIQUAL group',
                                         'T2 diagnose quality','Dwi diagnose quality','Dce diagnose quality')) 
dd$`Gwet AC1` <- paste(rep(" ", 5), collapse = " ")

# Set-up theme
tm <- forest_theme(base_size = 12,
                   refline_lty = "solid",
                   ci_pch = c(15, 18,17),
                   ci_col = c("#377eb8", "#4daf4a","red"),
                   ci_alpha=1, 
                   ci_lty=1.2,ci_lwd=2,
                   xaxis_lwd = 1.2,
                   footnote_col = "blue",
                   legent_position="top",
                   legend_name = "Reader comparison",
                   legend_value = c("Hannah vs Sangeet", "Hannah vs Nancy","Sangeet vs Nancy"))



# forest plot
p <- forest(dd[,c(10,11)],
            est = list(dd$hn_sg_gwet,
                       dd$hn_nc_gwet,
                       dd$sg_nc_gwet),
            lower = list(dd$hn_sg_lower,
                         dd$hn_nc_lower,
                         dd$sg_nc_lower), 
            upper = list(dd$hn_sg_upper,
                         dd$hn_nc_upper,
                         dd$sg_nc_upper),
            ci_column = c(2),sizes=0.5,
            xlim=c(0,1.1),
            nudge_y = 0.2,
            theme = tm)

plot(p)

**Comment by adayim** [comment]
It's not the argument, change your code `dd$Gwet AC1 <- paste(rep(" ", 5), collapse = " ")` to `dd$Gwet AC1 <- paste(rep(" ", 20), collapse = " ")` or larger number of blanks. I thought I had a comment for this line in the vignette example.
