### ISSUE TITLE
Adjusting line ends of confidence intervals?

### ISSUE THREAD

**Issue by TACdeVries** [adayim/forestploter#38]
Dear Adayim,

Is is possible to adjust the line end of the confidence intervals? The standard seems to be 'round' but I'd prefer using either 'butt' or 'square'. See this [stackoverflow weblink](https://stackoverflow.com/questions/10941650/change-plotted-segment-ends-from-round-to-flat) or this picture below for more information. I can't find the option in 'forest_theme' to adjust this graphical parameter. It can't seem to be find a possibility to adjust this directly in the forest function.

![image](https://user-images.githubusercontent.com/126504479/223181644-bb2c0234-9c42-4c24-9262-680e9291250d.png).

My apologies for the frequent requests these last couple of days. 

Thanks,
Tim

**Comment by adayim** [comment]
Hi Tim,

It is easy to edit the theme function, but I haven't thought through how to make it work for multiple groups. The multiple groups causing me lots of headaches. I can easily do that, but I am not going to touch that for now. You can also edit the graphical parameters by `edit_plot`:
```r
g <- edit_plot(g, col = 4, which = "ci",  gp = gpar(lineend= "round"))
```
Column 4 is where you put your CI.
