### ISSUE TITLE
Group multiple meta-analyses in one plot?

### ISSUE THREAD

**Issue by jgonzhijon** [adayim/forestploter#40]
Hi,

First of all, thank you very much for this package, it is very intuitive and the result is excellent.

What I would like to say is that a few months ago I used the foresploter package for some research I was doing in which I needed to plot two dimensions of data. I had to plot 4 meta-analyses of depression according to the severity status of relatives who suffered from covid in 4 cohorts (see image). (here is the DOI of the preprint in case you want to see it [10.1101/2023.02.28.23286559](https://doi.org/10.1101/2023.02.28.23286559))

![model_1_hosp_phq9](https://user-images.githubusercontent.com/53370002/230097707-9270420e-ce62-4941-9def-f78b46732e83.jpg)

At that time like June 2022, with version '0.1.6'. I was able to modify the aesthetic in this way:

```{r}
prueba2<-forest(forest_dat_model1_phq9_hosp_alt[,c(1,6,7)],
       est = forest_dat_model1_phq9_hosp_alt$PR,
       lower = forest_dat_model1_phq9_hosp_alt$conf.low, 
       upper = forest_dat_model1_phq9_hosp_alt$conf.high,
       sizes = as.numeric(forest_dat_model1_phq9_hosp_alt$std.error),
       ci_column = 2,
       arrow_lab = c("less", "more"),
       xlim = c(0.8, 3),
       ticks_at = c(0.8, 1, 1.5, 2, 3), 
       is_summary = c(rep(FALSE, nrow(forest_dat_model1_phq9_hosp_alt)-4), rep(TRUE,4)),
       ref_line = 1,
       theme = tm)

z<-prueba2$grobs

#iceland
z[[134]]$children[[1]]$gp$col<-"#B0A565"
z[[134]]$children[[2]]$gp$col<-"#B0A565"

z[[135]]$children[[1]]$gp$col<-"#FF7844"
z[[135]]$children[[2]]$gp$col<-"#FF7844"

z[[136]]$children[[1]]$gp$col<-"#E14594"
z[[136]]$children[[2]]$gp$col<-"#E14594"

#map
z[[138]]$children[[1]]$gp$col<-"#B0A565"
z[[138]]$children[[2]]$gp$col<-"#B0A565"

z[[139]]$children[[1]]$gp$col<-"#FF7844"
z[[139]]$children[[2]]$gp$col<-"#FF7844"

z[[140]]$children[[1]]$gp$col<-"#E14594"
z[[140]]$children[[2]]$gp$col<-"#E14594"

z[[141]]$children[[1]]$gp$col<-"#2F86A6"
z[[141]]$children[[2]]$gp$col<-"#2F86A6"

#sct
z[[143]]$children[[1]]$gp$col<-"#2F86A6"
z[[143]]$children[[2]]$gp$col<-"#2F86A6"

#swe

z[[145]]$children[[1]]$gp$col<-"#B0A565"
z[[145]]$children[[2]]$gp$col<-"#B0A565"

z[[146]]$children[[1]]$gp$col<-"#FF7844"
z[[146]]$children[[2]]$gp$col<-"#FF7844"

z[[147]]$children[[1]]$gp$col<-"#E14594"
z[[147]]$children[[2]]$gp$col<-"#E14594"

z[[148]]$children[[1]]$gp$col<-"#2F86A6"
z[[148]]$children[[2]]$gp$col<-"#2F86A6"

#overall
z[[150]]$gp$col<-"#B0A565"
z[[150]]$gp$fill<-"#B0A565"

z[[151]]$gp$col<-"#FF7844"
z[[151]]$gp$fill<-"#FF7844"

z[[152]]$gp$col<-"#E14594"
z[[152]]$gp$fill<-"#E14594"

z[[153]]$gp$col<-"#2F86A6"
z[[153]]$gp$fill<-"#2F86A6"



prueba2$grobs<-z
prueba2<-edit_plot(prueba2, row = c(1,3,5,7,9,11,13,15,17,19,21), which = "background",
                   gp = gpar(fill = "white"))

prueba2$grobs[[1]]$label<-"Cohort (ref. Relative not infected)"

ggsave(filename = "./images_metanalysis/model_1_hosp_phq9.jpg", plot = prueba2,dpi = 800,
       width = 8, height = 6, units = "in")
```

However, even if I use version 0.1.6 and it works perfectly, in current versions it can no longer be done. I'm simply writing here to ask if there is any way in later versions to be able to do this type of graph (since I don't have much knowledge of grob) and if not, have you thought about implementing it in the package or in the guide an easier way to be able to make this type of groups in the graph?

Thank you very much!!

Best,
Juan

**Comment by adayim** [comment]
Hi Juan,
Thank you for your feedback. Can you try the following:
```r
g <- edit_plot(g, col = 2, row = 2, which = "ci", 
          gp = gpar(col = "#B0A565", fill = "#B0A565"))
```
You can use `edit_plot` to edit text, background and whiskers. Also, please note that the calculation of the point is changed. You have to do it manually. [Here](https://github.com/adayim/forestploter/issues/37#issuecomment-1450208581) is a discussion on the calculation.
