### ISSUE TITLE
How to change the appearance of text per column ?

### ISSUE THREAD

**Issue by Nozomi-Kurihara** [adayim/forestploter#41]
I have read the Introduction to forestploter, but there is something I can't figure out, so I would like to ask a question.

As shown in the attached table, I want to align each cell in the subgroup columm to the left. I want to center all other cells in the column.

![forest](https://user-images.githubusercontent.com/87927089/232670867-4bacebea-9cef-4868-872b-334de9676746.png)

I tried to adjust it with `core = `, but I could change it per row, but not per column.
I also tried `edit_plot()` to change the text color per column, but not the alignment. (I tried using `just =`)

If there is a way to do this, I would appreciate it.

**Comment by adayim** [comment]
Hi, have you tried the following for the center alignment? Which is presented [here](https://cran.r-project.org/web/packages/forestploter/vignettes/forestploter-post.html#edit-plot)

```r
g <- edit_plot(g, col = 9:14, 
               which = "text",
               # gp = gpar(),
               hjust = unit(0.5, "npc"),
               x = unit(0.5, "npc"))
```

**Comment by Nozomi-Kurihara** [comment]
Thank you for your answer.

I read "Post-editing forestplot" from the link you provided. 
I am sorry that I did not get to that material before asking my question.

I have edited the script as you suggested and it looks exactly as I expected.

I am sorry that I did not check enough.
Thank you for your excellent package.

**Comment by adayim** [comment]
That's all right. Maybe I didn't write it clear enough.
