### ISSUE TITLE
Break the axes

### ISSUE THREAD

**Issue by cug-xyx** [adayim/forestploter#44]
Dear author:

Thanks for your excellent R package that solved the problem of my lazy friend who do not wanna write code.

There is a problem in drawing: **sometimes a CI lines is too long for other data to be presented better.**

![1685418138084](https://github.com/adayim/forestploter/assets/77427610/51c6f1d1-9b0a-4af7-92b6-9067c3451a12)

Could you please add a parameter for **breaking the axes** or do you have any good suggestions?

And i hope that the p-values will be presented in the current graph in the future versions of this Rpkg.

Thanks again

**Comment by adayim** [comment]
Hi, you can use `x_trans` to change the scale of the x-axis. Also, you can add anything you want, including p-value. Provide it in the data. Frame. For example, include your p-value column next to the HR 95% CI. You should be able to find it in the vignettes.

**Comment by cug-xyx** [comment]
Thank you for your reply dude! 😍 
And i will try it as soon as possible and then give you a response.

**Comment by cug-xyx** [comment]
> Excuse me, I wonder did you finally break the axes?

@Kalfredwv 
No, i just used `x_trans = 'log'` argument to reduce the distance.

**Comment by Kalfredwv** [comment]
Alright, thanks for your timely reply.
