### ISSUE TITLE
How can I make a specified column display with superscripts or subscripts?

### ISSUE THREAD

**Issue by banduoba** [adayim/forestploter#45]
For example, when I am plotting a forest plot, if one of the study subjects has a subscript like PM2.5, how can I make the 2.5 display as a subscript?

When I was drawing a forest plot, there was a column of numbers that I needed to express in scientific notation with superscripts. I found that the expression() function can be used to add superscripts when plotting graphs, for example:

```
library("lattice") 
y <- x <- 1:10
xyplot(y ~ x, main = expression(paste("Title ", 10^2, " abcd")))
```
![image](https://github.com/adayim/forestploter/assets/4811366/f25c67bc-cf40-41d2-9b6f-a2c16a68ee22)

I wanted to use the expression() function on a specified column when drawing the forest plot, so that the plot could display properly with superscripts or subscripts. Please advise how I can write this code.

**Comment by adayim** [comment]
Hi, please check out the `add_text` or `insert_text` help. Checkout the issue #27 .
