### ISSUE TITLE
How do I change these TEXT fontsize

### ISSUE THREAD

**Issue by 42kuroniko** [adayim/forestploter#46]
![image](https://github.com/adayim/forestploter/assets/136058430/6fb12aab-a50d-4743-9146-dac1ebfe361e)
![image](https://github.com/adayim/forestploter/assets/136058430/f224058c-a51e-4395-9952-4166845f98db)

I know these can be edited in theme function ,but I don't know what these called, how do i set the parameters instead changing it in my PDF editor.

Thanks for your help.

**Comment by adayim** [comment]
You can set the header in the theme function `xaxis_cex` for xaxis label and #29 for the header with `cex`. Also [here](https://cran.r-project.org/web/packages/forestploter/vignettes/forestploter-post.html). But remember, `xaxis_cex` will also change the size of the  ticks.

**Comment by 42kuroniko** [comment]
> 

it's not like what I expected, so there is no another way to only edit the header?

**Comment by adayim** [comment]
I am not sure if you have looked at the documentation at all. You should be able to edit text with `edit_plot` function OR change the theme by adding `colhead=list(fg_params=list(fontsize=8))`.
