### ISSUE TITLE
Argument 'background' misspelled in add_grob function

### ISSUE THREAD

**Issue by nicholasf9400** [adayim/forestploter#47]
Hello,

I thought I would let you know that in line 89 of the add_grob function, the word 'background' is misspelled as 'backgroud'. This caused me some issues, it might do the same to other people, but appears to be an easy fix, so I thought you should know.

Great package otherwise!

Thanks

**Comment by adayim** [comment]
Thanks, I should have performed a spell check.

**Comment by adayim** [comment]
This has been fixed now and closing. Thank you again for reporting this.
