### ISSUE TITLE
How to change legend size?

### ISSUE THREAD

**Issue by sdsdkklgy** [adayim/forestploter#54]
I want to change the size of the legend, but I found that there is no relevant code in the introduction:forest_theme.

**Comment by adayim** [comment]
I don't think there's a way to change the legend size. I will add a feature for this.

**Comment by Sifan-T** [comment]
> I don't think there's a way to change the legend size. I will add a feature for this.

Hi,
In your legend_grob.R:
legend_grob <- function(name = "",
                        label,
                        position = c("right", "top", "bottom"),
                        hgap = unit(0.1, "lines"), #horizontal gap
                        vgap = unit(0.5, "lines"), #vertical gap
                        pch = 15,
                        gp = gpar(lty = 1,
                                  col = "black",
                                  fill = "black",
                                  fontsize = 12,
                                  fontfamily = "")
may adding "cex=?" in parameter "gp" work?
good time

**Comment by adayim** [comment]
Sorry, I was busy. I have added option to change legend size and you can change it by specifying different values for `legend_cex` in `forest_theme`.

**Comment by sdsdkklgy** [comment]
Sorry for the delayed response;  I'm delighted the command is working! However, another potential issue is that the legend's text and visuals overlap when you zoom in. Anyway, I much appreciate the update!

**Comment by adayim** [comment]
Glad it works. Can you paste the output here so I can make sure it works properly?
