### ISSUE TITLE
Multiple summary diamond shapes for multiple CI columns

### ISSUE THREAD

**Issue by hoangtm97** [adayim/forestploter#55]
Hi Alimu,

I wonder if you could add a new feature where we can add multiple summary diamond shapes for multiple CI columns. The "is_summary" argument is currently not valid for multiple groups. In many cases, it seems better for me to combine some similar forest plots into one.

**Comment by adayim** [comment]
Yes, it does not allow you to have group for the summary diamond as it will stuck together. I am not sure if it is a good practice to do that.

**Comment by hoangtm97** [comment]
I understand your point. As I have a compelling reason to do so, can you find any way to modify the function to allow multiple summary shapes for multiple CIs?

**Comment by adayim** [comment]
Hi, I have updated the package on GitHub. Can you try it and let me if it is working as expected? Thank you.

**Comment by hoangtm97** [comment]
That worked now. Thank you so much.
