### ISSUE TITLE
Error in grid.Call.graphics(C_setviewport, vp, TRUE) :    invalid 'layout.pos.col'

### ISSUE THREAD

**Issue by hoangtm97** [adayim/forestploter#57]
Hi,
I tried to add circle grobs to the plot using this code:
# Draw circle grob
cols <- c(rep('#cc0000',3),rep('#00cc00',6))
symb <- c('1','2','3','4','5','6','7','8','9')
for(i in seq_along(symb)){
  pos <- which(forest_data == symb[i], arr.ind=TRUE)
  for(j in 1:nrow(pos)){
    forest_plot <- add_grob(forest_plot, 
                            row=pos[j,1], 
                            col=pos[j,2],
                            order='background',
                            gb_fn=circleGrob,
                            r=0.4,
                            gp=gpar(fill = cols[i]))
  }
}

The code is fine, I think. But when plotting, the following error occurred:
Error in grid.Call.graphics(C_setviewport, vp, TRUE) : 
  invalid 'layout.pos.col'

Can you take a look at this and suggest what to do?

Thank you.

**Comment by adayim** [comment]
Sorry, you didn't give me code to recreate the issues you have. I can't help you unless there's an example code that I can try.

**Comment by hoangtm97** [comment]
Here it is:

temp_rma <- binom.bayes(data_race$b5801_scar, data_race$scar)
forest_data <- data.frame(
  label=c(as.character(data_race$study),'','Total (95% CI)','Total HLA-B*58:01'),
  b5801=c(data_race$b5801_scar,'','837',''),
  total=c(data_race$scar,'','937',''),
  estim=c(round(temp_rma$mean,2),'','0.90',''),
  lower=c(round(temp_rma$lower,2),'','0.86',''),
  upper=c(round(temp_rma$upper,2),'','0.94',''),
  st_er=c(sqrt(weights(m_a)/10),'',1,''),
  weigh=c(sprintf('%.1f%%',weights(m_a)),'','100%',''),
  ci_95=c(sprintf('%.2f [%.2f, %.2f]',temp_rma$mean, temp_rma$lower, temp_rma$upper),'',
          '0.90 [0.86, 0.94]',''),
  blank=rep('',27),
  s_nos=c(data_race$s,'','',''),
  c_nos=c(data_race$c,'','',''),
  e_nos=c(data_race$e,'','',''),
  nos  =c(data_race$nos,'','','')
)

# Plot
font_size <- 8
theme <- forest_theme(core=list(fg_params=list(hjust=1, x=0.9),
                                bg_params=list(fill=c('white'))),
                      colhead=list(fg_params=list(hjust=c(0,1,1,1,1,1,1,1,1,1),
                                                  x=c(0.05,0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.9))),
                      summary_col='black', arrow_label_just='end', arrow_type='closed',
                      base_size=font_size)

forest_plot <- forest(forest_data[,c(1:3,8:14)],
                      est=forest_data$estim, lower=forest_data$lower, upper=forest_data$upper,
                      sizes=forest_data$st_er, ci_column=6, xlim=c(0,1), ticks_at=c(0,0.5,1),
                      is_summary=c(rep(FALSE, 22), TRUE, rep(FALSE, 7), TRUE, rep(FALSE, 3), TRUE, FALSE),
                      theme=theme)

# Draw circle grob
cols <- c(rep('#cc0000',3),rep('#00cc00',6))
symb <- c('1','2','3','4','5','6','7','8','9')
for(i in seq_along(symb)){
  pos <- which(forest_data == symb[i], arr.ind=TRUE)
  for(j in 1:nrow(pos)){
    forest_plot <- add_grob(forest_plot, 
                            row=pos[j,1], 
                            col=pos[j,2],
                            order='background',
                            gb_fn=circleGrob,
                            r=0.4,
                            gp=gpar(fill = cols[i]))
  }
}

plot(forest_plot, autofit=F)

I am attaching the plot without the circle grob as well. Every other detail in the code was fine, but when I ran the code for circle grob, the error occurs.

<img width="617" alt="Screenshot 2023-12-27 at 05 09 04" src="https://github.com/adayim/forestploter/assets/63577126/83b9ce43-131b-4699-90f3-19aca74c298a">

**Comment by hoangtm97** [comment]
I think your recommended code for the grob will also draw circles for numbers in columns 2 and 3 of the plot as well, but let's skip that and just focus on how to fix that error.

**Comment by adayim** [comment]
Hi, I think this is caused by your data.  You used subset of the data when you are drawing the forest plot `forest_data[,c(1:3,8:14)]`, but you used full data set when for the `circleGrob`.  The row and columns you provided will be wrong. The package works perfectly fine.

Try to change `pos <- which(forest_data == symb[i], arr.ind=TRUE)` to `pos <- which(forest_data[,c(1:3,8:14)] == symb[i], arr.ind=TRUE)` .

**Comment by hoangtm97** [comment]
Thanks. It works now. Really appreciate your help.
