### ISSUE TITLE
The forest plot is not centered.

### ISSUE THREAD

**Issue by ltj-github** [adayim/forestploter#58]
![Uploading Snipaste_2024-01-14_15-34-03.png…]()

The forest plot is not centered. The forest plot is located on the upper side

**Comment by ltj-github** [comment]
The forest plot is not centered. The forest plot is located on the upper side
![Uploading Snipaste_2024-01-14_15-34-03.png…]()

**Comment by ltj-github** [comment]
The forest plot is not centered. The forest plot is located on the upper side
![Snipaste_2024-01-14_15-34-03](https://github.com/adayim/forestploter/assets/56884953/3c71ef7b-8712-4311-9f2c-06b2e98c95b3)

**Comment by antoine-baldassari** [comment]
Hello, could the fix be added to the CRAN release? Alternatively, could you point to the commit where the issue was fixed?

**Comment by ltj-github** [comment]
Hello, it's caused by my parameter setting conflict, and the package is fine.

**Comment by antoine-baldassari** [comment]
I see, thank you for the quick reply. I started noticing the CI no longer aligned with the center of the rows, and this issue had led me to think it might have started in 1.1.1. Presumably something about our grid theme must not be quite right. Sorry for the red herring!
