### ISSUE TITLE
How to change the default background color?

### ISSUE THREAD

**Issue by ayue2019** [adayim/forestploter#6]
Thank you for this great work to help us draw beautiful forest plots.
Is it possible to provide an argument to change the default background color?
![image](https://user-images.githubusercontent.com/58946586/161523217-7f7375bc-12d6-4d6b-9531-e16a56db72f0.png)

Thank you very much !

**Comment by adayim** [comment]
Yes, you can change that easily. 
Try this:
```r
tm <- forest_theme(core = list(bg_params = list(fill = blues9[1:4], col=NA)))
```
And pass `tm` to `forest` as `theme = tm`. This fill backgroud color with blues9[1:4] and it will be recycled.

You can find some examples [here](https://cran.r-project.org/web/packages/gridExtra/vignettes/tableGrob.html)

**Comment by ayue2019** [comment]
That 's cool ! Thank you really much !
