### ISSUE TITLE
"The confidence interval line that extends beyond the x-axis limit does not appear in the plot."

### ISSUE THREAD

**Issue by Ble11** [adayim/forestploter#61]
Please help
"When I generate a forest plot, I receive the following warning: 'The confidence interval of row 7, column 3, group 1 is outside of the xlim.' Consequently, there is no visible confidence interval line for row 7. I would like the ends of the confidence interval lines to be marked with arrowheads to indicate that the CI extends beyond the displayed range."

I have already tried deleting ci_Theight, but there has been no response.
This is my code: 
tm <- forest_theme(base_size = 10,
                   # Confidence interval point shape, line type/color/width
                   ci_pch = 15,
                   ci_col = "black",
                   ci_fill = "black",
                   ci_alpha = 0.8,
                   ci_lty = 1,
                   ci_lwd = 1.5,ci_Theight = 0.2, # Set a T end at the end of CI 
                   # Reference line width/type/color
                   refline_gp = gpar(lwd = 1, lty = "dashed", col = "grey20"),
                   # Vertical line width/type/color
                   vertline_lwd = 1,
                   vertline_lty = "dashed",
                   vertline_col = "grey20",
                   arrow_type = "closed",
                   colhead=list(fg_params = list(parse=FALSE)), 
                   core=list(fg_params = list(parse=parse_mat)))

p <- forestploter::forest(data15[,c(1:2,6:7)],
            est = data15$est,
            lower = data15$low,
            upper = data15$hi,  
            size = 0.4,
            ci_column = 3,
            ref_line = 0,
            xlim = c(-15, 15),
            ticks_at = c(-12,-8,-4,0,4,8,14),
            xlab = " standardized mean difference",
            theme = tm
            )

p <- edit_plot(p,
               row = c(1, 5),
               gp = gpar(fontface = "bold"))
print(p)
![wmd](https://github.com/adayim/forestploter/assets/169509444/9531a36e-0e23-4960-ae48-d14fe01b6346)

**Comment by adayim** [comment]
Hi,

It would be difficult to define a starting point for a line that are outside of the xlim. This is a normal behavior. You can add a footnote to explain this.

**Comment by Ble11** [comment]
Thank you for your answer. I was wondering if I could do it like the example usage of forestploter shown in the figure below.
There is an arrow at the end of the line when the value exceeds the limit of the x-axis. I tried running the code in the basic usage of forestploter 
<img width="520" alt="Screenshot 2567-05-14 at 09 18 03" src="https://github.com/adayim/forestploter/assets/169509444/9b952dfe-c3fb-463a-9610-c37927ed4dc8">
that you provided, and there were no problems with the confidence interval. It produced the same forest plot as yours. Can you tell me which part of the code I should adjust to produce the arrow at the end of the line?"

**Comment by adayim** [comment]
I think in your case, your values are outside of the xlim. Which means your lower CI larger than the maximum of xlim or the upper CI smaller than minimum xlim. There will be no arrows in this case. 

The plot you showed only works if the lower CI smaller than maximum xlim or upper CI larger than minimum xlim.

**Comment by Ble11** [comment]
Thank you for your answer. I'm not sure I understand 'correctable'. My x-limit is -15 to 15. My estimate is 12.31, my upper CI is 23.39, and my lower CI is 1.23. Therefore, my lower CI is smaller than the maximum x-limit. I'm not sure where the problem is.

**Comment by Ble11** [comment]
Thank you for taking the time to help me. I have already sent the email. My email is ble_sama@hotmail.com.

**Comment by Ble11** [comment]
"It works now. Thank you so much. You made my day."
