### ISSUE TITLE
How to amend whiskers

### ISSUE THREAD

**Issue by ziqiuduofu** [adayim/forestploter#63]
Thank you very much for providing such a great R package. 

I read in the literature that there is a way to change the ci_lty and ci_lwd values for specific rows, but it seems that edit_plot does not affect "ci" when I use it.  I just want to remove the whiskers in spesific rows.

Should I modify the input in the original data or the theme?

**Comment by adayim** [comment]
Why not just set that value to missing? The package will not draw the missing value.

**Comment by ziqiuduofu** [comment]
Thank you very much for your reply. 

I have tried to set the lower and upper values to NA for a specific row, but this causes the OR value box to disappear as well. 

In my results, the whiskers overlap with the box, but I only want to remove the whiskers. 

<img width="545" alt="image" src="https://github.com/adayim/forestploter/assets/80271567/30b7d0d4-47e4-4341-9e16-8d0adc692e51">

Thanks again for your kindness.

**Comment by adayim** [comment]
Of course, it will stop drawing everything, the point as well. Are you saying you want to keep the point estimation but not the whiskers?

**Comment by ziqiuduofu** [comment]
I've solved it by altering ci_Theight, thank you again.
