### ISSUE TITLE
Right Adjust Cell

### ISSUE THREAD

**Issue by thejokingpenguin** [adayim/forestploter#65]
Hi Adayim
Really enjoy your work!
Just one question I can't seem to figure out, is it possible to change the adjustment of a text column?

**Comment by adayim** [comment]
Hi, you can align the text before with `forest_theme` function or after with `edit_plot` function. You can find example [here](https://cran.r-project.org/web/packages/forestploter/vignettes/forestploter-intro.html#text-justification-and-background-with-theme) to change the alignment before and [here](https://cran.r-project.org/web/packages/forestploter/vignettes/forestploter-post.html#edit-plot) after.
