### ISSUE TITLE
Change legend location

### ISSUE THREAD

**Issue by martaalcalde** [adayim/forestploter#66]
Hi! I was wondering if it is possible to change the legend position. By default it is located on the right-hand size of the figure and in two rows, but I would like it to have it on the top and in a single row (two columns), as showing in the following figure:

![image](https://github.com/user-attachments/assets/a93a740e-5ed0-41d1-a052-d71b5923b38a)

Thank you very much!

**Comment by adayim** [comment]
Hi, have you tried the `legend_position = "top"` parameters in `forest_theme` function?

**Comment by martaalcalde** [comment]
Thank you!!
