### ISSUE TITLE
xlim=NULL does not work.

### ISSUE THREAD

**Issue by niekverw** [adayim/forestploter#7]
Great package, best forest plotter there is probably in R! 

I am getting an error when I set the argument xlim manually to null (e.g. forestploter::forest(...,xlim=NULL)
>Error in if (any(unlist(est) < 0, na.rm = TRUE) || any(unlist(lower) <  :  missing value where TRUE/FALSE needed
  
 I suspect that on this line it should be !is.null(xlim) instead of !missing(xlim)
 
 https://github.com/cran/forestploter/blob/f8d6a5a43e8ce19941d513c60baf84394a8666ef/R/forest.R#L107

**Comment by adayim** [comment]
Hi, do you have any reproduceable exmaple that I can check? I thought `missing` also check the `NULL` and my examples works just fine after I set `xlim=NULL`.

**Comment by niekverw** [comment]
Thanks! ah, I see it happens if you set ,xlog = T. 

e.g. using the example forestplot:

> forest(dt[,c(1:3, 8:9)],
            est = dt$est,
            lower = dt$low,
            upper = dt$hi,
            sizes = dt$se,
            ci_column = 4,
            ref_line = 1,
            arrow_lab = c("Placebo Better", "Treatment Better"),
            xlim=NULL,xlog = T,
            ticks_at = c(0.5, 1, 2, 3),
            footnote = "This is the demo data. Please feel free to change\nanything you want.",
            theme = tm)
            
vs 



> forest(dt[,c(1:3, 8:9)],
            est = dt$est,
            lower = dt$low,
            upper = dt$hi,
            sizes = dt$se,
            ci_column = 4,
            ref_line = 1,
            arrow_lab = c("Placebo Better", "Treatment Better"),
            xlog = T,
            ticks_at = c(0.5, 1, 2, 3),
            footnote = "This is the demo data. Please feel free to change\nanything you want.",
            theme = tm)

**Comment by adayim** [comment]
Em, this is not an issue to be honest. You should not have `xlim` parameters set to `NULL` if you are not going to define the `xlim`. The default is `NULL`. I am gussing the `missing` checks if the parameter is used or not. I will change it to `NULL` later, this is not a critical issue. Thanks for the reporting.

**Comment by niekverw** [comment]
Thanks so much, no it is not really an issue, but if you want to set xlim inside another function, you need to pass xlim and then it wouldn't work. Thanks again.

**Comment by niekverw** [comment]
It works great!, thanks!
